In [778]:

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import joblib
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
df = pd.read_csv("Swift 599.csv")
df

ID                                SWIFT_MT599_MESSAGE  \
0    426  {1:F0 1DMCTVWXXX329762846}{2:I599PGPOIOXXXN}{4...   
1    299  {1:F01EKLAPZXXX237910045}{2:I599DRPQGVXX::XN}{...   
2    816  {1:F01FLZCECXXX638299601}{2:I599TXFDFWXXXN}{4:...   
3    266  {1:F01QCFSXAXXX745599627}{2:I599GFOHHLXXXN}{4:...   
4    720  {1:F01EBREJYXXX315778570}{2:I599DWCSGDXXXN}{4:...   
..   ...                                                ...   
368  742  {1:F01UBFHZPXXX559633772}{2:I599GUQNZSXXXN}{4:...   
369  727  {1:F01YPJIOYXXX428282745}{2:I599EUDUAXXXXN}{4:...   
370  587  {1:F01VLYKMTXXX172040770}{2:I599WDXJVGXXXN}{4:...   
371  845  {1:F01RDWCGWXXX472984957}{2:I599WFHWRXXXXN}{4:...   
372  956  {1:F01QMGYFTXXX699741663}{2:I599YHKUX,,,HXXXN}...   

                 CATEGORY         SUBCATEGORY URGENCY  
0                     NaN  funds_availability    high  
1       transaction_query                 NaN  medium  
2    payment_confirmation  funds_availability    high  
3    payment_confirmation  funds_availability    high  
4    payment_confirmation             receipt  medium  
..                    ...                 ...     ...  
368  payment_confirmation  funds_availability     low  
369  payment_confirmation             receipt    high  
370  payment_confirmation  funds_availability     low  
371            regulatory          compliance     low  
372  payment_confirmation             receipt     low  

[373 rows x 5 columns]

In [724]:
pd.set_option('display.max_columns', None)
df


ID                                SWIFT_MT599_MESSAGE  \
0    426  {1:F0 1DMCTVWXXX329762846}{2:I599PGPOIOXXXN}{4...   
1    299  {1:F01EKLAPZXXX237910045}{2:I599DRPQGVXX::XN}{...   
2    816  {1:F01FLZCECXXX638299601}{2:I599TXFDFWXXXN}{4:...   
3    266  {1:F01QCFSXAXXX745599627}{2:I599GFOHHLXXXN}{4:...   
4    720  {1:F01EBREJYXXX315778570}{2:I599DWCSGDXXXN}{4:...   
..   ...                                                ...   
368  742  {1:F01UBFHZPXXX559633772}{2:I599GUQNZSXXXN}{4:...   
369  727  {1:F01YPJIOYXXX428282745}{2:I599EUDUAXXXXN}{4:...   
370  587  {1:F01VLYKMTXXX172040770}{2:I599WDXJVGXXXN}{4:...   
371  845  {1:F01RDWCGWXXX472984957}{2:I599WFHWRXXXXN}{4:...   
372  956  {1:F01QMGYFTXXX699741663}{2:I599YHKUX,,,HXXXN}...   

                 CATEGORY         SUBCATEGORY URGENCY  
0                     NaN  funds_availability    high  
1       transaction_query                 NaN  medium  
2    payment_confirmation  funds_availability    high  
3    payment_confirmation  funds_availability    high  
4    payment_confirmation             receipt  medium  
..                    ...                 ...     ...  
368  payment_confirmation  funds_availability     low  
369  payment_confirmation             receipt    high  
370  payment_confirmation  funds_availability     low  
371            regulatory          compliance     low  
372  payment_confirmation             receipt     low  

[373 rows x 5 columns]

In [725]:
# Drop the 'ID' column
df.drop(columns=['ID'], inplace=True)

In [726]:
# --- Numeric Summary ---
print(">> Numeric Summary:\n")
print(df.describe())  


>> Numeric Summary:

                                      SWIFT_MT599_MESSAGE  \
count                                                 352   
unique                                                352   
top     {1:F0 1DMCTVWXXX329762846}{2:I599PGPOIOXXXN}{4...   
freq                                                    1   

                    CATEGORY         SUBCATEGORY URGENCY  
count                    323                 360     355  
unique                     6                  14       3  
top     payment_confirmation  funds_availability     low  
freq                     167                  88     123  


In [727]:
# --- Categorical Summary ---
print("\n>> Categorical Summary:\n")
print(df.describe(include='object'))


>> Categorical Summary:

                                      SWIFT_MT599_MESSAGE  \
count                                                 352   
unique                                                352   
top     {1:F0 1DMCTVWXXX329762846}{2:I599PGPOIOXXXN}{4...   
freq                                                    1   

                    CATEGORY         SUBCATEGORY URGENCY  
count                    323                 360     355  
unique                     6                  14       3  
top     payment_confirmation  funds_availability     low  
freq                     167                  88     123  


In [728]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 373 entries, 0 to 372
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   SWIFT_MT599_MESSAGE  352 non-null    object
 1   CATEGORY             323 non-null    object
 2   SUBCATEGORY          360 non-null    object
 3   URGENCY              355 non-null    object
dtypes: object(4)
memory usage: 11.8+ KB


In [729]:
print("\n>> Missing Values per Column:\n")
print(df.isnull().sum())
df_dropped = df.dropna(subset = ['SWIFT_MT599_MESSAGE'],inplace=True)
print(df)


>> Missing Values per Column:

SWIFT_MT599_MESSAGE    21
CATEGORY               50
SUBCATEGORY            13
URGENCY                18
dtype: int64
                                   SWIFT_MT599_MESSAGE              CATEGORY  \
0    {1:F0 1DMCTVWXXX329762846}{2:I599PGPOIOXXXN}{4...                   NaN   
1    {1:F01EKLAPZXXX237910045}{2:I599DRPQGVXX::XN}{...     transaction_query   
2    {1:F01FLZCECXXX638299601}{2:I599TXFDFWXXXN}{4:...  payment_confirmation   
3    {1:F01QCFSXAXXX745599627}{2:I599GFOHHLXXXN}{4:...  payment_confirmation   
4    {1:F01EBREJYXXX315778570}{2:I599DWCSGDXXXN}{4:...  payment_confirmation   
..                                                 ...                   ...   
368  {1:F01UBFHZPXXX559633772}{2:I599GUQNZSXXXN}{4:...  payment_confirmation   
369  {1:F01YPJIOYXXX428282745}{2:I599EUDUAXXXXN}{4:...  payment_confirmation   
370  {1:F01VLYKMTXXX172040770}{2:I599WDXJVGXXXN}{4:...  payment_confirmation   
371  {1:F01RDWCGWXXX472984957}{2:I599WFHWRXXXXN}{4:

In [780]:

df.CATEGORY.unique()


array([nan, 'transaction_query', 'payment_confirmation', 'regulatory',
       'customer_comms', 'error', 'bank_details'], dtype=object)

In [732]:
df.CATEGORY.value_counts()


CATEGORY
payment_confirmation    156
regulatory               32
transaction_query        30
customer_comms           30
error                    29
bank_details             27
Name: count, dtype: int64

In [733]:
df.SUBCATEGORY.unique()


array(['funds_availability', nan, 'receipt', 'sanctions', 'documentation',
       'details', 'account_issue', 'format', 'compliance', 'processing',
       'verification', 'update', 'data', 'status', 'beneficiary_query'],
      dtype=object)

In [734]:
df.SUBCATEGORY.value_counts()

SUBCATEGORY
funds_availability    85
receipt               72
processing            29
verification          23
compliance            21
sanctions             16
format                16
documentation         15
account_issue         14
status                14
update                13
data                   9
details                8
beneficiary_query      8
Name: count, dtype: int64

In [735]:


df.loc[df['SUBCATEGORY'] == 'sanctions', 'CATEGORY'] = 'regulatory'
df.loc[df['SUBCATEGORY'] == 'compliance', 'CATEGORY'] = 'regulatory'
df.loc[df['SUBCATEGORY'] == 'funds_availability', 'CATEGORY'] = 'payment_confirmation'
df.loc[df['SUBCATEGORY'] == 'receipt', 'CATEGORY'] = 'payment_confirmation'
df.loc[df['SUBCATEGORY'] == 'account_issue', 'CATEGORY'] = 'customer_comms'
df.loc[df['SUBCATEGORY'] == 'beneficiary_query', 'CATEGORY'] = 'customer_comms'
df.loc[df['SUBCATEGORY'] == 'update', 'CATEGORY'] = 'bank_details'
df.loc[df['SUBCATEGORY'] == 'verification', 'CATEGORY'] = 'bank_details'
df.loc[df['SUBCATEGORY'] == 'processing', 'CATEGORY'] = 'transaction_query'
df.loc[df['SUBCATEGORY'] == 'status', 'CATEGORY'] = 'transaction_query'
df.loc[df['SUBCATEGORY'] == 'documentation', 'CATEGORY'] = 'transaction_query'
df.loc[df['SUBCATEGORY'] == 'details', 'CATEGORY'] = 'transaction_query'
df.loc[df['SUBCATEGORY'] == 'data', 'CATEGORY'] = 'error'
df.loc[df['SUBCATEGORY'] == 'format', 'CATEGORY'] = 'error'


In [736]:
# Export to a new CSV file
df.to_csv("cleaned_with_false.csv", index=False)

In [737]:
import pandas as pd
import re

# Load CSV file
df = pd.read_csv("Swift 599.csv")  

# Function to extract :79: field
def extract_79_field(message):
    match = re.search(r":79:(.*?)\n-}", str(message), re.DOTALL)  # Convert message to string (handles NaN cases)
    return match.group(1).strip() if match else None

# Overwrite the column with extracted content
df["SWIFT_MT599_MESSAGE"] = df["SWIFT_MT599_MESSAGE"].apply(extract_79_field)

# Drop the 'ID' column
df.drop(columns=['ID'], inplace=True)

# Display the updated DataFrame
print(df)

# Optionally, save the cleaned data back to CSV
df.to_csv("cleaned_swift_messages.csv", index=False)

                                   SWIFT_MT599_MESSAGE              CATEGORY  \
0    CONFIRMATION OF FUNDS RECEIPT FOR INVOICE RR78...                   NaN   
1    QUERY REGARDING STATUS OF TRANSACTION REF NW36...     transaction_query   
2    CONFIRMATION OF FUNDS   RECEIPT FOR INVOICE GF...  payment_confirmation   
3    CONFIRMATION OF FUNDS RE!!!CEIPT FOR INVOICE K...  payment_confirmation   
4    CONFIRMATION OF FUNDS R::ECEIPT FOR INVOICE TE...  payment_confirmation   
..                                                 ...                   ...   
368  CONFIRMATION OF FUNDS RECEIPT FOR INVOICE JW19...  payment_confirmation   
369  FUNDS NOW AVAI!!!LABLE FOR TRANSACTION ST39216...  payment_confirmation   
370  CONFIRMATION  OF FUNDS RECEIPT FOR INVOICE HK2...  payment_confirmation   
371  SCREENING ALER!!!T POTENTIAL SANCTIONS MATCH\n...            regulatory   
372  CONFIRMATION OF FUNDS RECEIPT FOR INVOICE RT34...  payment_confirmation   

            SUBCATEGORY URGENCY  
0    

In [738]:
# Preprocessing tools
lemmatizer = WordNetLemmatizer()

import re
import string

def clean_text(text):
    # Lowercase
    text = text.lower()
    # Remove digits and punctuation
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Apply the clean_text function
df['SWIFT_MT599_MESSAGE'] = df['SWIFT_MT599_MESSAGE'].astype(str).apply(clean_text)

df

SWIFT_MT599_MESSAGE              CATEGORY  \
0    confirmation of funds receipt for invoice rr a...                   NaN   
1    query regarding status of transaction ref nw p...     transaction_query   
2    confirmation of funds receipt for invoice gf a...  payment_confirmation   
3    confirmation of funds receipt for invoice kw a...  payment_confirmation   
4    confirmation of funds receipt for invoice te a...  payment_confirmation   
..                                                 ...                   ...   
368  confirmation of funds receipt for invoice jw a...  payment_confirmation   
369  funds now available for transaction st value date  payment_confirmation   
370  confirmation of funds receipt for invoice hk a...  payment_confirmation   
371  screening alert potential sanctions match part...            regulatory   
372  confirmation of funds receipt for invoice rt a...  payment_confirmation   

            SUBCATEGORY URGENCY  
0    funds_availability    high  
1                   NaN  medium  
2    funds_availability    high  
3    funds_availability    high  
4               receipt  medium  
..                  ...     ...  
368  funds_availability     low  
369             receipt    high  
370  funds_availability     low  
371          compliance     low  
372             receipt     low  

[373 rows x 4 columns]

In [739]:
# Preprocessing tools
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text_nlp(text):
    text = text.lower()
    text = re.sub(r'\W+', ' ', text)
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(t) for t in tokens if t not in stop_words]
    return ' '.join(tokens)

In [772]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE
import joblib

# Load your dataset
df = pd.read_csv("cleaned_with_false.csv")

# Step 1: Encode labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df['CATEGORY'])

# Step 2: Vectorize text using TF-IDF
vectorizer = TfidfVectorizer(max_features=500)
X = vectorizer.fit_transform(df['SWIFT_MT599_MESSAGE'])

# Step 3: Handle class imbalance with SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Step 4: Train model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_resampled, y_resampled)

# Step 5: Save the model, vectorizer, and label encoder
joblib.dump(model, "random_forest_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")
joblib.dump(label_encoder, "label_encoder.pkl")

print("Model, vectorizer, and encoder saved successfully.")


Model, vectorizer, and encoder saved successfully.


In [741]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from collections import Counter
# 5. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.3, random_state=42, stratify=y_resampled
)

# 6. Train Random Forest
rf = RandomForestClassifier(random_state=42, n_estimators=50, max_depth=10, min_samples_leaf=1)
rf.fit(X_train, y_train)

# 7. Predict and evaluate
y_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le.classes_))

Accuracy: 0.9417808219178082

Confusion Matrix:
 [[48  0  0  0  0  0]
 [ 0 48  0  0  0  0]
 [ 0  0 49  0  0  0]
 [ 0  0  0 49  0  0]
 [ 0  0  0  0 49  0]
 [ 0  6 11  0  0 32]]

Classification Report:
                       precision    recall  f1-score   support

        bank_details       1.00      1.00      1.00        48
      customer_comms       0.89      1.00      0.94        48
               error       0.82      1.00      0.90        49
payment_confirmation       1.00      1.00      1.00        49
          regulatory       1.00      1.00      1.00        49
   transaction_query       1.00      0.65      0.79        49

            accuracy                           0.94       292
           macro avg       0.95      0.94      0.94       292
        weighted avg       0.95      0.94      0.94       292



In [742]:
# Predict on training set
y_pred_train = rf.predict(X_train)

# Calculate training accuracy
training_accuracy = accuracy_score(y_train, y_pred_train)

print("Training Accuracy :", training_accuracy)

Training Accuracy : 0.9720588235294118


In [744]:
import os
os.getcwd()


'C:\\Users\\itssr'

In [776]:
import streamlit as st
import joblib

# Load the trained components
model = joblib.load("random_forest_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")
label_encoder = joblib.load("label_encoder.pkl") 

# Streamlit UI
st.title("SWIFT MT599 Category Predictor")
st.write("Enter a SWIFT MT599 message to predict its category.")

input_text = st.text_area("Enter message here:")

if st.button("Predict"):
    if input_text.strip():
        # Transform the user input
        features = vectorizer.transform([input_text])

        # Make prediction
        prediction = model.predict(features)

        # Convert label back to original
        label = label_encoder.inverse_transform(prediction)[0]

        st.success(f"Predicted Category: {label}")
    else:
        st.warning("Please enter some text.")
